/* eslint-disable react/jsx-key */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import * as React from 'react';
import { styled } from '@mui/material/styles';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import ButtonBase from '@mui/material/ButtonBase';
import { grey } from '@mui/material/colors';

const defaultEndpoint = 'https://rickandmortyapi.com/api/character/'
const Img = styled('img')({
  margin: 'auto',
  display: 'block',
  maxWidth: '100%',
  maxHeight: '100%',
});

export async function getServerSideProps(context) {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data
    }, // will be passed to the page component as props
  }
}

export default function  ComplexGrid({data}) {
  const { results = []} = data;
  console.log('data', data);
  return (
      <div className={styles.container}>
      <Head>
        <title>Rick And Morty Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Rick And Morty <a href="https://rickandmortyapi.com/">API Using Next.JS!</a>
        </h1>

        <p className={styles.description}>
          Play around with Rick And Morty API at {' '}
          <code className={styles.code}>rickandmortyapi.com</code>
        </p>
        <ul className={styles.grid}>
        {results.map(result => {
            const {id, name, image, status, location, origin, species, gender, url} = result;
            return(
              <li key={ id }  className={styles.card}>
                <Grid container item xs={15} spacing={2}>
                  <Grid item>
                    <ButtonBase sx={{ width: 200, height: 200 }}>
                      <Img alt="complex" src={image}></Img>
                    </ButtonBase>
                  </Grid>
                  <Grid item xs={15} sm container>
                    <Grid item xs={15} container direction="column" spacing={2}>
                      <Grid item xs>
                        <Typography gutterBottom variant="h2" style={{ fontSize:30}} className={styles.hover}>
                        <a href={url} id>{ name }</a>
                        </Typography>
                        <Typography variant="body2" gutterBottom>
                          { status }
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                          Last Known Location:
                        </Typography>
                        <Typography variant="body2" gutterBottom className={styles.hover}>
                          <a href={location.url}>{ location.name }</a>
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                          First Seen in:
                        </Typography>
                        <Typography variant="body2" gutterBottom className={styles.hover}>
                          <a href={origin.url}>{ origin.name }</a>
                        </Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                </Grid>
              </li>
            )
          })}
          
        </ul>
        

        <ul className={styles.grid}>
          <li  className={styles.card}>
                <a href="https://nextjs.org/docs">
                </a>
              </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>    
  )
}
